### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by center-777** [visionmedia/page.js#501]
After upgrade to `1.10.0` i got an error: 
![image](https://user-images.githubusercontent.com/7359520/45222173-62717a80-b2bc-11e8-9616-3f28aa05f13e.png)

https://github.com/visionmedia/page.js/blob/v1.10.0/index.js#L53

**Comment by matthewp** [comment]
Hm, that is unexpected. Can you go to that line and let me know what `this` is?

**Comment by flootr** [comment]
[We experience the same error](https://github.com/Automattic/wp-calypso/pull/27061). `this` seems to be defined correctly defined but `_onpopstate` is undefined at this point and therefore can't be bound.

The only thing I could spot why that might be is the following [piece of code](https://github.com/visionmedia/page.js/blob/v1.10.0/index.js#L431-L433):

```js
  Page.prototype._onpopstate = (function () {
    var loaded = false;
    if ( ! hasWindow ) {
      return;
    }
```

which evaluates to `false` and returns `undefined` instead of a function which could be bound.

**Comment by matthewp** [comment]
@flootr Can you confirm that returning a function there instead fixes it? `return function(){};` should be enough.

**Comment by flootr** [comment]
@matthewp that does indeed help. Can't speak for the issue author though.

**Comment by nthibert** [comment]
When will this actually make it out. When I do a npm install for my project, I get 1.10.0 down and I get this error as well. I know it was fixed but just wondering when this will make it live?

**Comment by matthewp** [comment]
I'll do a release today.

**Comment by matthewp** [comment]
Released in 1.10.2

**Comment by flootr** [comment]
@matthewp not sure what went wrong but 1.10.2 doesn't seem to include that fix. Ha, it seems my PR from above only fixed it for `page.js`, not `index.js` and `index.mjs` 🤔

**Comment by matthewp** [comment]
Oh, sorry I didn't look at that closely enough. `page.js` and `page.mjs` get generated from `index.js`. So changes should be made to `index.js`. I'll reopen since this is not fixed.

**Comment by nthibert** [comment]
Thanks for looking into this.
